# Generated by Django 3.2.7 on 2021-09-13 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examination_name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=10)),
                ('questions_and_solutions', models.JSONField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam_period', models.TimeField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField()),
                ('education_qualification', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField()),
                ('education_qualification', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_start_date_time', models.DateTimeField()),
                ('student_solutions', models.JSONField(default=dict)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.teacher'),
        ),
    ]
