# Generated by Django 3.2.7 on 2021-09-13 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('date_of_birth', models.DateField()),
                ('education_qualification', models.JSONField()),
            ],
        ),
    ]
